AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  github-actions-with-aws-sam

  Sample SAM Template for github-actions-with-aws-sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
  Api:
      Cors:
          AllowMethods: "'GET,POST,OPTIONS'"
          AllowHeaders: "'content-type'"
          AllowOrigin: "'*'"

Resources:
  GenerateSchedulesFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: Backend/
      Handler: src.endpoints.generate_schedules_lambda_handler
      Runtime: python3.11
      MemorySize: 1024
      Architectures:
      - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: carleton-courses
      Events:
        GenerateSchedules:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /generateSchedules
            Method: post
  
  GetTermsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Backend/
      Handler: src.endpoints.get_terms_lambda_handler
      Runtime: python3.11
      MemorySize: 2048
      Architectures:
      - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: carleton-courses
      Events:
        GenerateSchedules:
          Type: Api
          Properties:
            Path: /getTerms
            Method: get

  GetCoursesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Backend/
      Handler: src.endpoints.get_courses_lambda_handler
      Runtime: python3.11
      MemorySize: 1024
      Architectures:
      - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: carleton-courses
      Events:
        GenerateSchedules:
          Type: Api
          Properties:
            Path: /getCourses
            Method: get

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GenerateSchedulesApi:
    Description: API Gateway endpoint URL for generating a list of possible schedules.
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/generateSchedules/"
  GenerateSchedulesFunction:
    Description: Generate Schedules Lambda Function ARN
    Value: !GetAtt GenerateSchedulesFunction.Arn
  GenerateSchedulesFunctionIamRole:
    Description: Implicit IAM Role created for Generate Schedules Function
    Value: !GetAtt GenerateSchedulesFunctionRole.Arn
  GetTermsApi:
    Description: API Gateway endpoint URL for generating a list of the current terms.
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/getTerms/"
  GetTermsFunction:
    Description: Get Terms Lambda Function ARN
    Value: !GetAtt GetTermsFunction.Arn
  GetTermsFunctionIamRole:
    Description: Implicit IAM Role created for Get Terms Function
    Value: !GetAtt GetTermsFunctionRole.Arn
  GetCoursesApi:
    Description: API Gateway endpoint URL for generating a list of the courses for a given term.
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/getCourses/"
  GetCoursesFunction:
    Description: Get Courses Lambda Function ARN
    Value: !GetAtt GetCoursesFunction.Arn
  GetCoursesFunctionIamRole:
    Description: Implicit IAM Role created for Get Courses Function
    Value: !GetAtt GetCoursesFunctionRole.Arn
