AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Other lambda functions used for webscraping

Globals:
  Function:
    Timeout: 3

Parameters:
  executionRole:
    Type: String
    Description: ARN of the IAM role for execution

Resources:
  Bs4Layer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: bs4_layer
      Description: python beautifulsoup4 layer
      CompatibleRuntimes:
        - python3.11
      Content:
        S3Bucket: carletonschedulingtool
        S3Key: lambda-layers/bs4_layer.zip

  ParseClassDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: WebScraping/functions/parser
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      MemorySize: 1028
      Timeout: 900
      Role: !Ref executionRole
      Layers:
        - !Ref Bs4Layer
      Architectures:
        - x86_64

  CreateTableFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: WebScraping/functions/createTable
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      MemorySize: 128
      Timeout: 600
      Role: !Ref executionRole
      Architectures:
        - x86_64

  DeleteTableFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: WebScraping/functions/deleteTable
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      MemorySize: 128
      Timeout: 600
      Role: !Ref executionRole
      Architectures:
        - x86_64

  InsertClassDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: WebScraping/functions/insertData
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      MemorySize: 128
      Timeout: 600
      Role: !Ref executionRole
      Architectures:
        - x86_64