AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Docker image lambda function
  
Globals:
  Function:
    Timeout: 3

Parameters:
  executionRole:
    Type: String
    Description: ARN of the IAM role for execution

Resources:
  GetClassHrefsFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 1028
      Timeout: 900
      Role: !Ref executionRole
    Metadata:
      DockerTag: latest
      DockerContext: ./WebScraping/functions/navigation
      Dockerfile: Dockerfile