on:
    push:
      branches:
        - main
jobs:
    build-deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
        - uses: aws-actions/setup-sam@v1
        - uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
        # sam build 
        - run: sam build --use-container
  
  # Run Unit tests- Specify unit tests here 
        - run: pip install -r Backend/tests/requirements.txt
        - run: coverage run -m pytest Backend/tests/unit -v 
        - run: coverage report
  
  # sam deploy
        - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name SchedulerBackend --s3-bucket carletonschedulingtool --capabilities CAPABILITY_IAM --region us-east-1