on:
    push:
      branches:
        - main
      paths:
        - WebScraping/functions/parser/**
        - WebScraping/functions/deleteTable/**
        - WebScraping/functions/insertData/**
jobs:
    build-deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: aws-actions/setup-sam@v1
        - uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
            
        # sam build 
        - run: sam build --use-container --template-file webscraping-template.yaml

        # Run Unit tests
        - run: pip install -r WebScraping/tests/requirements.txt
        - run: coverage run --branch -m pytest WebScraping/tests/unit -v
        - run: coverage report -m
  
        # sam deploy
        - run: |
            sam deploy \
              --no-confirm-changeset --no-fail-on-empty-changeset --stack-name WebScraper --s3-bucket carletonschedulingtool \
              --capabilities CAPABILITY_IAM --region us-east-1 --parameter-overrides 'executionRole=${{ secrets.EXECUTION_ROLE }}'